/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-07 19:07:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

if(session.getAttribute("user") != null){
    response.sendRedirect("pages/user/dashboard.jsp");
    return;
}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>QuizMaster - The Ultimate Battle</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/vars.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animations.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        .hero {\n");
      out.write("            height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            text-align: center;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .hero h1 {\n");
      out.write("            font-size: 5rem;\n");
      out.write("            font-weight: 900;\n");
      out.write("            margin: 0;\n");
      out.write("            line-height: 1.1;\n");
      out.write("            letter-spacing: -2px;\n");
      out.write("            animation: slideInUp 1s cubic-bezier(0.16, 1, 0.3, 1);\n");
      out.write("        }\n");
      out.write("        .hero p {\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            color: var(--text-secondary);\n");
      out.write("            max-width: 600px;\n");
      out.write("            margin: 20px 0 40px;\n");
      out.write("            animation: slideInUp 1s cubic-bezier(0.16, 1, 0.3, 1) 0.2s both;\n");
      out.write("        }\n");
      out.write("        .action-btns {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 20px;\n");
      out.write("            animation: slideInUp 1s cubic-bezier(0.16, 1, 0.3, 1) 0.4s both;\n");
      out.write("        }\n");
      out.write("        .btn-large {\n");
      out.write("            padding: 18px 40px;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            border-radius: 50px;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("        .btn-secondary {\n");
      out.write("            background: transparent;\n");
      out.write("            border: 2px solid var(--glass-border);\n");
      out.write("            color: var(--text-primary);\n");
      out.write("        }\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background: rgba(255,255,255,0.1);\n");
      out.write("        }\n");
      out.write("        .floating-element {\n");
      out.write("            position: absolute;\n");
      out.write("            background: linear-gradient(135deg, var(--accent-blue), var(--accent-purple));\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(80px);\n");
      out.write("            opacity: 0.5;\n");
      out.write("            z-index: -1;\n");
      out.write("        }\n");
      out.write("        .shape-1 { width: 300px; height: 300px; top: 10%; left: 10%; animation: float 6s infinite alternate; }\n");
      out.write("        .shape-2 { width: 400px; height: 400px; bottom: 10%; right: 10%; background: linear-gradient(135deg, var(--accent-purple), var(--accent-red)); animation: float 8s infinite alternate-reverse; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"floating-element shape-1\"></div>\n");
      out.write("    <div class=\"floating-element shape-2\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"hero\">\n");
      out.write("        <div class=\"badge animate-slide-up\" style=\"margin-bottom: 20px;\">v2.0 MASTER UPGRADE</div>\n");
      out.write("        <h1 class=\"gradient-text\">SURVIVE.<br>CONQUER.<br>ROAST.</h1>\n");
      out.write("        <p>12 insane game modes. Real-time battles. Zero mercy. Are you ready to prove your intelligence?</p>\n");
      out.write("        \n");
      out.write("        <div class=\"action-btns\">\n");
      out.write("            <a href=\"pages/auth/registration.jsp\" class=\"btn btn-large\">Join The Battle</a>\n");
      out.write("            <a href=\"pages/auth/login.jsp\" class=\"btn btn-large btn-secondary\">Login</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
